--CHECKING THE SIZE OF DATASET
SELECT 
	COUNT(*) AS TOTAL_NUMBER_OF_RECORDS
FROM 
	Suicides;

--CHECKING FOR NULL VALUES
SELECT
	count(*) AS TOTAL_NULL_VALUES
FROM
	Suicides
WHERE 
	STATE IS NULL or YEAR IS NULL OR Type_code IS NULL OR Type IS NULL 
	OR Gender IS NULL OR Age_group IS NULL OR Total IS NULL;

--CHECKING THE TOTAL NUMBER OF SUICIDES STATE-WISE
SELECT 
	STATE,COUNT(STATE) AS TOTAL_COUNT
FROM
	Suicides 
	GROUP BY State
	ORDER BY COUNT(STATE) DESC;

--WE ARE ABLE TO SEE THAT THERE ARE CERTAIN VALUES SUCH AS Total(All India),Total(States),Total(Uts)
--THESE VALUES CAN BE REMOVED FROMT THE DATASET BEFORE FURTHER ANALYSIS.

SELECT 
	*
FROM
	Suicides 
	WHERE State LIKE 'Total%';

DELETE FROM 
	Suicides 
	WHERE State LIKE 'Total%';

--NOW WE DON'T HAVE THAT VALUES
--CHECKING THE TOTAL NUMBER OF SUICIDES TYPE_CODE-WISE

SELECT
	Type_code,COUNT(Type_code) AS TOTAL_NUMBER_OF_SUICIDES
FROM 
	Suicides
	GROUP BY Type_code
	ORDER BY COUNT(Type_code) DESC;

--Total number of people who has committed suicide from 2001-2012
SELECT 
	YEAR,SUM(CAST(Total AS int)) as total 
FROM 
	Suicides
	where Type_code='Causes'
	GROUP BY YEAR
	ORDER BY YEAR ASC;

--CHECKING TOP 10 STATES WHERE SUICIDES ARE MORE:
WITH STATE_ANALYSIS AS
(SELECT 
	STATE,
	SUM(CAST(Total AS INT)) AS Suicides,
	DENSE_RANK() OVER(ORDER BY SUM(CAST(Total AS INT)) DESC) AS RANKS
FROM 
	Suicides
	WHERE Type_code= 'Causes'
	GROUP BY State) 
SELECT TOP 10 * FROM STATE_ANALYSIS;













